import COLORS from "tailwindcss/colors";
import { POKEMON_TYPES } from "./pokemonTypes";

export const POKEMON_TYPE_COLORS = {
  [POKEMON_TYPES.NORMAL]: COLORS.gray[400],
  [POKEMON_TYPES.FIGHTING]: COLORS.red[500],
  [POKEMON_TYPES.FLYING]: COLORS.blue[400],
  [POKEMON_TYPES.POISON]: COLORS.purple[600],
  [POKEMON_TYPES.GROUND]: COLORS.yellow[700],
  [POKEMON_TYPES.ROCK]: COLORS.yellow[600],
  [POKEMON_TYPES.BUG]: COLORS.green[500],
  [POKEMON_TYPES.GHOST]: COLORS.indigo[600],
  [POKEMON_TYPES.STEEL]: COLORS.gray[300],
  [POKEMON_TYPES.FIRE]: COLORS.red[600],
  [POKEMON_TYPES.WATER]: COLORS.blue[500],
  [POKEMON_TYPES.GRASS]: COLORS.green[400],
  [POKEMON_TYPES.ELECTRIC]: COLORS.yellow[400],
  [POKEMON_TYPES.PSYCHIC]: COLORS.pink[500],
  [POKEMON_TYPES.ICE]: COLORS.blue[200],
  [POKEMON_TYPES.DRAGON]: COLORS.indigo[800],
  [POKEMON_TYPES.DARK]: COLORS.gray[800],
  [POKEMON_TYPES.FAIRY]: COLORS.pink[300],
  [POKEMON_TYPES.UNKNOWN]: COLORS.teal[500],
  [POKEMON_TYPES.SHADOW]: COLORS.gray[800],
};
